### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by michallaskowski** [SDSWanderer/hipchat-markdown#1]
Hey, just found this gem. Would love to have Markdown support in Hipchat. Could you share what is the current status of the project? (Not a JS, Hipchat integrations expert); what needs to be done, if there is help needed?

**Comment by DanielHreben** [comment]
Hi! Main functionality is done already, but before upload to the atlassian market I need to fix a bug with formatting of some tricky messages.
You can already install and use latest version of this plugin from here - http://hipchat-markdown.herokuapp.com/

**Comment by DanielHreben** [comment]
I think I will finish it on next weekend. if you have some proposals how to make it better, or find some bugs - issues\requests are very welcome.

**Comment by DanielHreben** [comment]
Well, this weekend finally came. Stride has been released!
